##
##  ansi-recolor -- Transform ANSI Color Sequences of TUI Applications
##  Copyright (c) 2026 Dr. Ralf S. Engelschall <rse@engelschall.com>
##  Licensed under MIT license
##

#   static code analysis (linting)
lint
    eslint --config etc/eslint.mjs src/*.ts

#   static code analysis (linting) with file watching
lint-watch
    nodemon --exec "npm start lint" --watch src --ext ts

#   code compilation/transpiling (building) with file watching
build-watch
    nodemon --exec "npm start build" --watch src --ext ts

#   build entire project
build : lint build-cmd build-man

#   build command program
build-cmd
    tsc --project etc/tsc.json 

#   build manual page
build-man
    remark --quiet --use remark-man --output dst/ansi-recolor.1 src/ansi-recolor.md

#   remove regularly built files
clean
    shx rm -rf dst

#   remove all built files
clean-dist : clean
    shx rm -f package-lock.json
    shx rm -rf node_modules

